// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-GraviteRTB",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-GraviteRTB", targets: ["AATKit-GraviteRTB"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        .package(url: "https://github.com/AddApptr/RTBSDK.git", .upToNextMinor(from: "1.11.0-beta1")),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-GraviteRTB",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    .product(name: "RTBSDK", package: "RTBSDK"),
                    "AATGraviteRTBAdapter",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-GraviteRTB"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATGraviteRTBAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATGraviteRTBAdapter.zip",
            checksum: "ba4a87061965fb44337565612660844d0e5055ec67dc64914b169ce1febd8358"
        ),
    ]
)
